version: "3.2"
services:
  php:
    build:
      context: .
    image: webuxmotion/ishop:1.0.0
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=ishop-mysql-app
      - MYSQL_USER=ishopuser
      - MYSQL_PASSWORD=ishoppass
      - MYSQL_DB=ishop_db
    volumes:
      - ./:/var/www/html/
    ports:
      - "40001:80"
    container_name: ishop-php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=ishopuser
      - MYSQL_PASSWORD=ishoppass
      - MYSQL_DATABASE=ishop_db
    container_name: ishop-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "40002:80"
    environment:
      - PMA_HOST=ishop-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: ishop-phpmyadmin-app
networks:
  frontend:
  backend:
